[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "stratified-disparity"
version = "0.1.0"

description = "A fairness metric for revealing hidden disparities in networked data through structural stratification."

readme = "README.md"

requires-python = ">=3.8"

license = {file = "LICENSE"}

authors = [
  {name = "Weixiang Wang"}
]

dependencies = [
  "numpy>=1.21",
  "pandas>=1.3",
  "networkx>=2.8",
  "matplotlib>=3.4",
  "scipy>=1.7",
  "kneed>=0.8"
]

[tool.setuptools.packages.find]
include = ["stratified_disparity*"]